### ISSUE TITLE
app2.py is not working anymore

### ISSUE THREAD

**Issue by ashgazer** [aickletfraid/PSNowGames#1]
Running app2.py does not generate any results. I believe this file is used to get the psnow data for europe.

**To Reproduce**
Python appy2.py
**Expected behavior**
generate a list of european psn now games

**Screenshots**
n/a

**Desktop (please complete the following information):**
Macos using virtual env

**Comment by aickletfraid** [comment]
Will check it out

**Comment by aickletfraid** [comment]
Thx for the fix @ashgazer .
Fix is  #2
